MovieWeb/Controllers/GenreController.cs
using API.Model;
using API.UriApi;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace MovieWeb.Controllers
{
    public class GenreController : Controller
    {
        private const string sController = "Genres/";
        private static string baseURI = BaseUriApi.GetUriWithController(sController);

        [HttpGet]
        public async Task<IActionResult> GetAllGenres(string search)
        {
            List<Genre> genres = new List<Genre>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseURI);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage result = null;
                if (search == null)
                {
                    result = await client.GetAsync("GetAllGenres");

                }
                else
                {
                    result = await client.GetAsync("GetGenreByName/searchByName?searchByName=" + search);

                }
                if (result.IsSuccessStatusCode)
                {
                    var resTask = result.Content.ReadAsStringAsync().Result;
                    genres = JsonConvert.DeserializeObject<List<Genre>>(resTask);
                }
            }

            return View(genres);
        }

        #region "Post Method"
        public IActionResult CreateGenre()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateGenre(Genre genre)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseURI);

                //Http Post
                var postTask = client.PostAsJsonAsync<Genre>("PostGenre", genre);
                postTask.Wait();

                var result = postTask.Result;
                //condition if it's ok
                if (result.IsSuccessStatusCode)
                {
                    ViewBag.msg = "Added successfully";
                    //return RedirectToAction("GetAllMovies");
                }
                else
                {
                    ViewBag.msg = "Something went wrong...";
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator");
                }
            }

            return View(genre);
        }
        #endregion

        #region "Put Method"
        [HttpGet]
        public async Task<ActionResult> EditGenreAsync(Guid id)
        {
            Genre genre = new Genre();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseURI);

                //Http Get
                var responseTask = client.GetAsync("GetGenreById/id?id=" + id.ToString());
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var resTask = result.Content.ReadAsStringAsync().Result;
                    genre = JsonConvert.DeserializeObject<Genre>(resTask);
                }
            }
            return View(genre);
        }

        public IActionResult EditGenre(Genre genre)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseURI);

                //Http Post
                var postTask = client.PutAsJsonAsync<Genre>("UpdateGenre/id?id=" + genre.IdGenre.ToString(), genre);
                postTask.Wait();

                var result = postTask.Result;
                //condition if it's ok
                if (result.IsSuccessStatusCode)
                {
                    ViewBag.msg = "Edit successfully";
                    //return RedirectToAction("GetAllMovies");
                }
                else
                {
                    ViewBag.msg = "Something went wrong...";
                    ModelState.AddModelError(string.Empty, "Server error. Please contact administrator");
                }
            }
            //v2
            //using (var client = new HttpClient())
            //{
            //    client.BaseAddress = new Uri("https://localhost:7165/api/");
            //    client.DefaultRequestHeaders.Clear();
            //    client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            //    HttpResponseMessage result = client.PutAsJsonAsync("Genres/" + genre.IdGenre.ToString(), genre).Result;
            //    if (result.IsSuccessStatusCode)
            //    {
            //        ViewBag.msg = "Edit successfully";
            //        ModelState.Clear();
            //    }
            //    else
            //    {
            //        ViewBag.msg = "Something went wrong...";
            //        ModelState.AddModelError(string.Empty, "Server error. Please contact administrator");

            //    }
            //}
            return View(genre);
        }
        #endregion

        #region "Delete Method"
        public IActionResult DeleteGenre(Guid id)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseURI);

                //HTTP DELETE
                var deleteTask = client.DeleteAsync("DeleteGenre/id?id=" + id.ToString());
                deleteTask.Wait();

                var result = deleteTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("GetAllGenres");
                }
            }

            return RedirectToAction("GetAllGenres");
        }
        #endregion

        #region "Details Method"
        [HttpGet]
        public async Task<IActionResult> GetGenre(Guid id)
        {
            Genre genre = new Genre();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseURI);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage result = await client.GetAsync("GetGenreById/id?id=" + id.ToString());
                if (result.IsSuccessStatusCode)
                {
                    var resTask = result.Content.ReadAsStringAsync().Result;
                    genre = JsonConvert.DeserializeObject<Genre>(resTask);
                }
            }
            return View(genre);
        }
        #endregion

        #region "Search Method By Name"
        [HttpGet]
        public async Task<IActionResult> SearchGenreByName(string genreByname)
        {
            Genre genre = new Genre();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(baseURI);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage result = await client.GetAsync("GetGenreByName/search=" + genreByname);
                if (result.IsSuccessStatusCode)
                {
                    var resTask = result.Content.ReadAsStringAsync().Result;
                    genre = JsonConvert.DeserializeObject<Genre>(resTask);
                }
            }
            return View(genre);
        }
        #endregion
    }
}

MovieWeb/Views/Genre/CreateGenre.cshtml
@model API.Model.Genre

@{
    ViewData["Title"] = "CreateGenre";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>In this page you can add a genre</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="CreateGenre">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display: none  ">
                <label asp-for="IdGenre" class="control-label"></label>
                <input asp-for="IdGenre" class="form-control" />
                <span asp-validation-for="IdGenre" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="GenreName" class="form-control" id="floatingInput" placeholder="the genre name" />
                <label asp-for="GenreName" for="floatingInput"></label>
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <p>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <button class="btn btn-secondary btnStyle"><a style="text-decoration:none; color:white" asp-action="GetAllGenres">Back to genres list</a></button>
                </div>
            </p>
        </form>
    </div>
</div>

@{
    try
    {
        if (ViewBag.msg != null)
        {
            <label style="color:darkgreen">@ViewBag.msg</label>
        }
    }
    catch (Exception)
    {
    }
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

MovieWeb/Views/Genre/EditGenre.cshtml
@model API.Model.Genre

@{
    ViewData["Title"] = "UpdateGenre";
}

<h1>In this page you can edit a genre</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="EditGenre">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group" style="display:none">
                <label asp-for="IdGenre" class="control-label"></label>
                <input asp-for="IdGenre" class="form-control" />
                <span asp-validation-for="IdGenre" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="GenreName" class="form-control" id="floatingInput" placeholder="the genre name" />
                <label asp-for="GenreName" for="floatingInput"></label>
                <span asp-validation-for="GenreName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary btnStyle" />
                <button class="btn btn-secondary" asp-action="GetAllGenres">Back to genres list</button>
            </div>
        </form>
    </div>
</div>

@{
    try
    {
        if (ViewBag.msg != null)
        {
            <label style="color:darkgreen">@ViewBag.msg</label>
        }
    }
    catch (Exception)
    {

    }
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

MovieWeb/Views/Genre/GetAllGenres.cshtml
@model IEnumerable<API.Model.Genre>
@*@model  IPagedList<API.Model.Movie> *@

@{
    ViewData["Title"] = "GetAllGenres";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="jumbotron bg-light bg-gradient text-secondary p-5 shadow-sm">
    <h1 class="display-4">Hello, in this page you ca see all the available genres movies.</h1>
    <p class="lead">Learn about API using ASP.NET 6.0 EF Core (Code First Approach). </p>
    <hr class="my-4">
    <p>List with all Genres</p>
    <a class="btn btn-sm btn-outline-info  " href="https://github.com/Boghian-Gabriel/API" role="button">Learn more about this project</a>
</div>

<div class="mt-4 d-flex justify-content-between mb-1">
    <div class="d-flex">
        <input type="submit" value="Create genre" class="btn btn-primary me-2 btnStyleLeft btnStyle " onclick="location.href='@Url.Action("CreateGenre", "Genre")'" />
    </div>

    @*search*@
    @using (Html.BeginForm("GetAllGenres", "Genre", FormMethod.Get))
    {
    <div class="d-sm-flex input-group">
        <input class="form-control" name="search" placeholder="Enter genre name" />
        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
    </div>
    }
</div>



<table class="table table-striped shadow-sm table-responsive table-bordered">
    <thead>
        <tr>
            <th class="text-center">
                @*@Html.DisplayNameFor(model => model.RealeseDate)*@
                @Html.ActionLink("GenreName", "GetAllGenres")
            </th>
            <th class="text-center">Actions</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.Count() != 0)
        {
            @foreach (var item in Model)
            {
                <tr>
                    <td style="display: none">
                        @Html.DisplayFor(modelItem => item.IdGenre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GenreName)
                    </td>
                    <td class="text-center">
                        <div class="btn-group">
                            @Html.ActionLink("Edit", "EditGenre", new {  id=item.IdGenre }, new { @class="btn btn-primary btnStyle" })
                            @Html.ActionLink("Details", "GetGenre", new { id=item.IdGenre }, new { @class="btn btn-success btnStyle" })
                            @Html.ActionLink("Delete", "DeleteGenre", new {  id=item.IdGenre }, new { @class="btn btn-danger btnStyle" })
                        </div>
                    </td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td class="text-center text-danger" colspan="4">
                    Nu exista informatii in baza de date!
                </td>
            </tr>
        }
    </tbody>
</table>

MovieWeb/Views/Genre/GetGenre.cshtml
@model API.Model.Genre

@{
    ViewData["Title"] = "GetGenre";
}


<h3 class="font-weight-bold"> The @Model.GenreName genre.</h3>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2" style="display:none">
            @Html.DisplayNameFor(model => model.IdGenre)
        </dt>
        <dd class="col-sm-10" style="display:none">
            @Html.DisplayFor(model => model.IdGenre)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>
        <dd class="col-sm-8">
            @Html.DisplayFor(model => model.GenreName)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "EditGenre", new {  id = Model.IdGenre }, new { @class="btn btn-primary btnStyle" })
    <button class="btn btn-secondary" type="submit" onclick="location.href='@Url.Action("GetAllGenres", "Genre")'">Back to genres List</button>
</div>